runtime: python311
env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  DATABASE_URL: projects/esgenerator/secrets/DATABASE_URL/versions/latest
  NVIDIA_API_KEY: projects/esgenerator/secrets/NVIDIA_API_KEY/versions/latest
  ALLOWED_ORIGINS: projects/esgenerator/secrets/ALLOWED_ORIGINS/versions/latest
  FRONTEND_URL: projects/esgenerator/secrets/FRONTEND_URL/versions/latest
  SECRET_KEY: projects/esgenerator/secrets/SECRET_KEY/versions/latest
  MAIL_SENDGRID_API_KEY: projects/esgenerator/secrets/MAIl_SENDGRID_API_KEY/versions/latest
  MAIL_DEFAULT_SENDER: projects/esgenerator/secrets/MAIL_DEFAULT_SENDER/versions/latest
  FLASK_ENV: production

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /.*
    script: auto
    secure: always