runtime: python311
env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6


handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /.*
    script: auto
    secure: always